services:
  - type: web
    name: biblioteca-interactiva
    runtime: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
      - key: PORT
        value: 10000
    plan: free
